version: '3.8'

services:
  zabbix-agent:
    image: '${ZABBIX_AGENT_IMAGE}'
    restart: always
    privileged: true
    ports:
      - 10050:10050
    env_file: .env
#     networks:
#       - shared_network

# networks:
#   shared_network:
#     external: true